// Writes src/deck-icons.ts: the icons a slide may draw with `<x-icon name>`.
//
// The key is the name a deck says, which is a format: decks already written
// name these, and the model is told the list. The value is the Jannchie icon
// drawn for it, at the regular weight.
//
//   pnpm icons
import { writeFileSync } from "node:fs"
import { createRequire } from "node:module"

const require = createRequire(import.meta.url)
const jannchie = require("@jannchie/iconify-json/icons.json")

/** A deck's name → the Jannchie icon drawn for it. */
const ICONS = {
  activity: "activity",
  add: "plus",
  analytics: "chart-combo",
  api: "code-braces",
  application: "layout-grid",
  "arrow-down": "arrow-down",
  "arrow-left": "arrow-left",
  "arrow-right": "arrow-right",
  "arrow-up": "arrow-up",
  "arrow-up-right": "arrow-up-right",
  badge: "award",
  book: "book-open",
  bot: "robot",
  building: "building",
  calendar: "calendar",
  camera: "camera",
  "chart-bar": "chart-bar",
  "chart-line": "chart-line",
  "chart-pie": "chart-pie",
  chat: "chat",
  checkmark: "check",
  "checkmark-outline": "check-circle",
  chip: "chip",
  close: "x",
  cloud: "cloud",
  code: "code",
  cube: "cube",
  "currency-dollar": "currency-dollar",
  dashboard: "gauge",
  "data-base": "database",
  "delivery-truck": "truck",
  document: "file-text",
  earth: "globe",
  education: "graduation-cap",
  email: "mail",
  "face-satisfied": "smile",
  favorite: "heart",
  flag: "flag",
  flash: "zap",
  folder: "folder",
  gift: "gift",
  group: "users",
  growth: "trending-up",
  help: "help",
  home: "home",
  idea: "lightbulb",
  image: "image",
  industry: "factory",
  information: "info",
  laptop: "laptop",
  link: "link",
  "list-checked": "list-check",
  location: "map-pin",
  locked: "lock",
  "machine-learning-model": "neural-network",
  map: "map",
  microphone: "mic",
  mobile: "smartphone",
  money: "banknote",
  moon: "moon",
  "network-3": "any-to-any",
  password: "key",
  phone: "phone",
  play: "play",
  "question-answering": "chats",
  rain: "cloud-rain",
  recycle: "recycle",
  rocket: "rocket",
  search: "search",
  security: "shield",
  send: "send",
  settings: "settings",
  "shopping-cart": "cart",
  star: "star",
  store: "store",
  subtract: "minus",
  sun: "sun",
  task: "task",
  "thumbs-up": "thumbs-up",
  time: "clock",
  "tool-kit": "toolbox",
  tools: "tools",
  tree: "tree",
  trophy: "trophy",
  user: "user",
  video: "video",
  wallet: "wallet",
  warning: "alert-circle",
  "warning-alt": "alert-triangle",
}

function drawing(name, drawn) {
  const icon = jannchie.icons[drawn] ?? fail(`Jannchie has no "${drawn}" (for "${name}").`)

  // The collection wraps each icon in the group that sets its stroke; the
  // deck's own <svg> sets that once, so only what is inside it is kept.
  return icon.body.replace(/^<g[^>]*>/, "").replace(/<\/g>$/, "")
}

function fail(message) {
  throw new Error(message)
}

/**
 * Names older decks use for a drawing another name already has. They still
 * draw, but are not offered: the picker and the model's list name each drawing
 * once. Carbon drew these apart (filled, outlined); Jannchie draws one line.
 */
const ALIASES = {
  "checkmark-filled": "checkmark-outline",
  lightning: "flash",
  "star-filled": "star",
  "user-multiple": "group",
}

const drawn = Object.values(ICONS)
const twice = drawn.find((icon, index) => drawn.indexOf(icon) !== index)

if (twice !== undefined) {
  fail(`"${twice}" is drawn for two names; make one an alias.`)
}

for (const [alias, name] of Object.entries(ALIASES)) {
  if (!Object.hasOwn(ICONS, name)) {
    fail(`The alias "${alias}" names "${name}", which is not an icon.`)
  }
}

const entries = Object.entries(ICONS)
  .map(([name, drawn]) => `  ${JSON.stringify(name)}: ${JSON.stringify(drawing(name, drawn))},`)
  .join("\n")

writeFileSync(
  new URL("../src/deck-icons.ts", import.meta.url),
  `/**
 * The icons a slide may draw with \`<x-icon name>\`: Jannchie Icons, by Jianqi
 * Pan (MIT), on their 24×24 grid at the regular weight.
 *
 * A closed set inlined here rather than an icon font or a CDN: a slide must
 * draw the same offline, in a download and in the PowerPoint file, which is
 * drawn from these same paths. The names are the deck format's, not the icon
 * set's, so a deck written before the drawings changed still names an icon.
 * Generated by \`scripts/generate-icons.mjs\`; to add one, add it there and run
 * it again.
 */

/** Each icon's inner SVG, on a 24×24 view box, stroked in \`currentColor\`. */
export const DECK_ICONS: Readonly<Record<string, string>> = {
${entries}
}

/** Older names for a drawing above: still drawn, not offered. */
const DECK_ICON_ALIASES: Readonly<Record<string, string>> = ${JSON.stringify(ALIASES)}

/** The names offered, to the picker and to the model: one per drawing. */
export const DECK_ICON_NAMES = Object.keys(DECK_ICONS)

/** The drawing a deck's name stands for, whether its own name or an older one; \`undefined\` for neither. */
export function deckIconBody(name: string): string | undefined {
  const own = Object.hasOwn(DECK_ICON_ALIASES, name) ? DECK_ICON_ALIASES[name]! : name

  return Object.hasOwn(DECK_ICONS, own) ? DECK_ICONS[own] : undefined
}

/** The whole drawing for an icon a deck names, or an empty one for a name it does not know. */
export function deckIconMarkup(name: string): string {
  const body = deckIconBody(name) ?? ""

  return \`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" role="img">\${body}</svg>\`
}
`,
)
